### ISSUE TITLE
Is possible to enable PSoC4 support in public ModusToolbox now?

### ISSUE THREAD

**Issue by misaz** [Infineon/mtb-example-psoc4-empty-app#1]
You have stated that this is prerelease software. Is possible to enable PSoC4 support in public ModusToolbox (2.2.0.2801) now If I want to some basic experiments with it before officialy released?

Do you plan any compatibility between PSoC6 and PSoC4 (when PDL and HAL is used)? Will be possible to migrate between PSoC4 and PSoC6 in some way?

**Comment by Harigovind-cy** [comment]
Yes. PSoC 4 will be publicly released very soon, enabling direct importing of this CE (along with several others). I'll update this thread once it is released.

At the moment, we are going to release with PDL support only. So it will require additional configuration and migrating between PSoC 4 and 6 will not be easily possible. You will have to re-write the entire application for PDL configuration.

**Comment by Harigovind-cy** [comment]
Hi, 

PSoC 4 support is officially released for MTB - [Just Released – PSoC 4® support in ModusToolbox](https://community.cypress.com/docs/DOC-21761). You can now import this and several other code examples directly from Eclipse IDE for MTB.
